host: "127.0.0.1"
port: 8848
namespace: "55dde173-9dbd-4100-b348-a5a1ece89ce6"
dataid: "account.json"
group: "prod"

#debug: false
#db:
#  host: "127.0.0.1"
#  port: 3308
#  dbName: "happy_account_mic_training"
#  userName: "root"
#  password: "123456"
#
#redis:
#  host: "127.0.0.1"
#  port: 6379
#
#consul:
#  host: "127.0.0.1"
#  port: 8500
#
#account_srv:
#  srvName: "account_srv"
#  host: "127.0.0.1"
#  port: 9095
#  tags:
#    - happy
#    - account_srv
#
#account_web:
#  srvName: "account_web"
#  host: "127.0.0.1"
#  port: 8081
#  tags:
#    - happy
#    - account_web